package pe.edu.unsch.entities;
// Generated 28/06/2019 07:38:29 PM by Hibernate Tools 5.2.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Docente generated by hbm2java
 */
@Entity
@Table(name = "docente", catalog = "cargabd")
public class Docente implements java.io.Serializable {

	private int idDocente;
	private String nombreDocente;
	private String tipoDocente;
	private Set<Semestre> semestres = new HashSet<Semestre>(0);

	public Docente() {
	}

	public Docente(int idDocente, String nombreDocente, String tipoDocente) {
		this.idDocente = idDocente;
		this.nombreDocente = nombreDocente;
		this.tipoDocente = tipoDocente;
	}

	public Docente(int idDocente, String nombreDocente, String tipoDocente, Set<Semestre> semestres) {
		this.idDocente = idDocente;
		this.nombreDocente = nombreDocente;
		this.tipoDocente = tipoDocente;
		this.semestres = semestres;
	}

	@Id

	@Column(name = "idDocente", unique = true, nullable = false)
	public int getIdDocente() {
		return this.idDocente;
	}

	public void setIdDocente(int idDocente) {
		this.idDocente = idDocente;
	}

	@Column(name = "nombreDocente", nullable = false, length = 45)
	public String getNombreDocente() {
		return this.nombreDocente;
	}

	public void setNombreDocente(String nombreDocente) {
		this.nombreDocente = nombreDocente;
	}

	@Column(name = "tipoDocente", nullable = false, length = 45)
	public String getTipoDocente() {
		return this.tipoDocente;
	}

	public void setTipoDocente(String tipoDocente) {
		this.tipoDocente = tipoDocente;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "docente")
	public Set<Semestre> getSemestres() {
		return this.semestres;
	}

	public void setSemestres(Set<Semestre> semestres) {
		this.semestres = semestres;
	}

}
