package pe.edu.unsch.entities;
// Generated 28/06/2019 07:38:29 PM by Hibernate Tools 5.2.10.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Semestre generated by hbm2java
 */
@Entity
@Table(name = "semestre", catalog = "cargabd")
public class Semestre implements java.io.Serializable {

	private SemestreId id;
	private Docente docente;
	private String nombreSemestre;
	private String horasSemanales;

	public Semestre() {
	}

	public Semestre(SemestreId id, Docente docente, String nombreSemestre, String horasSemanales) {
		this.id = id;
		this.docente = docente;
		this.nombreSemestre = nombreSemestre;
		this.horasSemanales = horasSemanales;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "idSemestre", column = @Column(name = "idSemestre", nullable = false)),
			@AttributeOverride(name = "docenteIdDocente", column = @Column(name = "Docente_idDocente", nullable = false)) })
	public SemestreId getId() {
		return this.id;
	}

	public void setId(SemestreId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Docente_idDocente", nullable = false, insertable = false, updatable = false)
	public Docente getDocente() {
		return this.docente;
	}

	public void setDocente(Docente docente) {
		this.docente = docente;
	}

	@Column(name = "NombreSemestre", nullable = false, length = 45)
	public String getNombreSemestre() {
		return this.nombreSemestre;
	}

	public void setNombreSemestre(String nombreSemestre) {
		this.nombreSemestre = nombreSemestre;
	}

	@Column(name = "HorasSemanales", nullable = false, length = 45)
	public String getHorasSemanales() {
		return this.horasSemanales;
	}

	public void setHorasSemanales(String horasSemanales) {
		this.horasSemanales = horasSemanales;
	}

}
